version: '3.7'
services:
  app:
    image: ukeweb/styleguide_devtools:0.8.1
    container_name: styleguide_devtools
    command: sh -c "npm i && npm run hmr-watch"
    ports:
      - 9000:9000
    volumes:
      - .:/app/node_modules/styleguide
